### ISSUE TITLE
After upgrade to Home Assistant 2022.4.5 breaks skola24

### ISSUE THREAD

**Issue by Zorkny** [TekniskSupport/home-assistant-skola24-to-ical#10]
After upgrade to 2022.4.5 it seems iCal-sensor doesn’t have start and end times it only has name, state (is the time it starts and subject) and friendly_name is the subject of the event. It’s the same for all iCal sensors I have, both file:// and google calendar - probably error in iCal-integration?

**Comment by TekniskSupport** [comment]
Sorry that i have not had the time to look at this until date

I just set up and tested, was this solved with a later update?
As far as i can see the sensors work as they should (i believe)

![image](https://user-images.githubusercontent.com/13868526/165355275-e4e5a412-e488-42f6-9ea3-60d4a246ba35.png)

**Comment by Zorkny** [comment]
Thank you, tried again to delete the integration and reinstall from HACS and added sources. Its working now!

**Comment by TekniskSupport** [comment]
Thanks for your patience
