### ISSUE TITLE
Error while setting up ical platform for sensor

### ISSUE THREAD

**Issue by fredamn76** [TekniskSupport/home-assistant-skola24-to-ical#7]
Hi.
The ical file is not created and i get the following error.

> Logger: homeassistant.components.sensor
> Source: custom_components/ical/__init__.py:122
> Integration: Sensor (documentation, issues)
> First occurred: 07:51:51 (1 occurrences)
> Last logged: 07:51:51
> 
> Error while setting up ical platform for sensor
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/config/custom_components/ical/sensor.py", line 47, in async_setup_entry
>     await ical_events.update()
>   File "/config/custom_components/ical/__init__.py", line 122, in update
>     async with session.get(self.url) as response:
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
>     self._resp = await self._coro
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 507, in _request
>     req = self._request_class(
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
>     self.update_host(url)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 366, in update_host
>     raise InvalidURL(url)
> aiohttp.client_exceptions.InvalidURL: %20file:///config/schedule.ics
>

**Comment by TekniskSupport** [comment]
This is actually raised from [https://github.com/TekniskSupport/ical-sensor-homeassistant](this) integration.

The path should not start with a space
